const AFFIRMATIONS = [
  "I am a soldier in the battle (2 Tim 2:3).",
  "I am a warrior for the Lord (Ex 15:3).",
  "I am a beloved child of God (1 Jn 3:1).",
  "I am the cause of the Father's joy (Is 62:4).",
  "I am God's masterpiece (Eph 2:10).",
  "I am fathered by God (Is 64:8).",
  "I am cared for by God (1 Pet 5:7).",
  "I am loved (1 Jn 4:9).",
  "I am blessed (Eph 1:3).",
  "I am chosen (Jn 15:16).",
  "I am rescued (Col 1:13).",
  "I am secure in Christ's love (Rom 8:39).",
  "I am never alone (Josh 1:9).",
  "I am not my past (2 Cor 5:17).",
  "I am no longer a slave to sin (Rom 6:6).",
  "I am a friend of Jesus (Jn 15:5).",
  "I am grateful (Ps 7:17).",
  "I am fearless (2 Tim 1:7).",
  "I am confident (Phil 4:13).",
  "I am obedient (Jn 15:14).",
  "I am sacrificial (Rom 12:1).",
  "I am patient (1 Cor 13:4).",
  "I am present to this moment (Mt 6:34).",
  "I am committed to prayer (Ps 141:2).",
  "I am the salt of the earth and the light of the world (Mt 5:13).",
  "I am pure of heart (Ps 24:4).",
  "I am surrounded by a great cloud of witnesses (Heb 12:1).",
  "I am on the journey (Ps 23).",
  "I am guided by the Holy Spirit (Gal 5:16).",
  "I am consecrated to Mary (Jn 19:26).",
  "I am consecrated to St. Joseph (Mt 1:25).",
  "I am protected by my Guardian Angel (Ps 91:11).",
  "I am hopeful (Jer 29:11).",
  "I can do all things through Christ who strengthens me (Phil 4:13).",
  "Be still and know that I am God (Ps 46:10).",
  "Trust in the Lord with all your heart (Prov 3:5).",
  "The Lord is my light and my salvation; whom shall I fear? (Ps 27:1).",
  "For I know the plans I have for you, says the Lord (Jer 29:11).",
  "Come to me, all you who are weary, and I will give you rest (Mt 11:28).",
  "Love one another as I have loved you (Jn 15:12).",
  "Do not be anxious about anything, but in every situation, present your requests to God (Phil 4:6).",
  "The Lord bless you and keep you (Num 6:24).",
  "With God all things are possible (Mt 19:26).",
];

const GOALS = [
  "Through Christ, wealth will come and an extraordinary life will be provided for my family.",
  "Through Christ, my business will be built today as an act of stewardship — He is my ultimate provider (Deut 8:18).",
  "Through Christ, excellence will flow through my work — my business is the vehicle He has given me to bless my family and the world.",
  "Through Christ, I will remember that every client, every deal, and every dollar is a gift of grace.",
  "Through Christ, I will be husband and father first, and businessman second, in every decision I make today.",
  "Through Christ, my wife and children will be provided with a life of abundance, security, and beauty — a reflection of the Father's generosity.",
  "Through Christ, wealth will be built not to be served, but to serve — my family, my Church, and my community.",
  "Through Christ, tithing will come first and Catholic causes and missions will be funded as a first act, not an afterthought.",
  "Through Christ, generosity will flow to those in need today — I cannot out-give God (Lk 6:38).",
  "Through Christ, a home worthy of the family He has entrusted to me will be owned.",
  "Through Christ, real estate and lasting assets will be built so that my children's children inherit a foundation of security.",
  "Through Christ, my family will be taken to extraordinary places and given memories that make them feel deeply loved and cared for.",
  "Through Christ, charities will be started and sustained that feed the hungry, shelter the homeless, and restore dignity to the forgotten.",
  "Through Christ, youth sports teams will be funded and children in my community will be given the opportunities I want for my own kids.",
  "Through Christ, I will be known in my Church community as someone who shows up and gives generously without recognition.",
  "Through Christ, I will be known in my neighbourhood as someone whose success lifts others, not just himself.",
  "Through Christ, I will never forget where I came from or who brought me to where I am going (Deut 8:18).",
  "Through Christ, success will make me more humble, more generous, and more grateful — not harder or prouder.",
  "Through Christ, my identity will remain rooted in being a child of God, not in my net worth or achievements.",
  "Through Christ, every major business decision will begin in prayer, surrendering my plans to God's will (Prov 16:3).",
  "Through Christ, I will be the same man in private that I am in public — grounded, faithful, and generous.",
  "Through Christ, children will be raised who understand that wealth is a responsibility and a gift, not a right.",
  "Through Christ, I will never stop building — there are always more people to help, more mouths to feed, more lives to change.",
  "Through Christ, everything I own will be held with an open hand, knowing it belongs to God and I am only the steward.",
];
