const AFFIRMATIONS = [
  "I am a soldier in the battle (2 Timothy 2:3, Psalm 144:1).",
  "I am a warrior for the Lord (2 Corinthians 4:7-12, Exodus 15:3).",
  "I am a beloved child of God (Mark 1:11, 1 John 3:1).",
  "I am the cause of the Father's joy (Isaiah 62:4, Mark 1:11).",
  "I am God's masterpiece (Ephesians 2:10, Psalm 139:13).",
  "I am fathered by God (Isaiah 64:8, Ephesians 2:10).",
  "I am cared for by God (1 Peter 5:7, Isaiah 43:1, Jeremiah 29:11).",
  "I am loved (1 John 4:9, Luke 15:8, 1 John 4:16).",
  "I am blessed (Ephesians 1:3, Philippians 4:19).",
  "I am chosen (John 15:16, Ephesians 1:4, 1 Peter 2:9).",
  "I am rescued (Colossians 1:13, John 3:16, Isaiah 43:1).",
  "I am secure in Christ's love (2 Corinthians 1:22, Romans 8:39).",
  "I am never alone (Joshua 1:9, Matthew 28:20, 1 Corinthians 6:19).",
  "I am not my past (Isaiah 43:18, 2 Corinthians 5:17, Revelation 21:5).",
  "I am no longer a slave to sin (Romans 6:6, Galatians 5:1).",
  "I am a friend of Jesus (John 15:5, John 15:9, John 15:11).",
  "I am grateful (Psalm 7:17, Psalm 139:13, Psalm 84:10).",
  "I am fearless (2 Timothy 1:7, Psalm 27:1, Psalm 60:12).",
  "I am confident (Psalm 27:3, Mark 9:23, Philippians 4:13).",
  "I am obedient (John 15:14, Proverbs 3:5-6, Matthew 7:21).",
  "I am sacrificial (Romans 12:1, John 17:19, Colossians 1:24).",
  "I am patient (1 Corinthians 13:4, Proverbs 19:2, Colossians 3:15).",
  "I am present to this moment (Matthew 6:34, Romans 12:2).",
  "I am committed to prayer (Psalm 141:2, John 15:4-5, Matthew 6:6).",
  "I am the salt of the earth and the light of the world (Matthew 5:13-14, Mark 16:15).",
  "I am pure of heart (Psalm 24:4-5).",
  "I am surrounded by a great cloud of witnesses (Hebrews 12:1).",
  "I am on the journey (Psalm 23, Hebrews 11:16).",
  "I am guided by the Holy Spirit (Galatians 5:16, Galatians 5:22-23).",
  "I am consecrated to Mary (John 19:26-27, Genesis 3:15).",
  "I am consecrated to St. Joseph (Matthew 1:25, Genesis 41:55).",
  "I am protected by my Guardian Angel (Matthew 18:10, Psalm 91:11, Psalm 34:7).",
  "I am hopeful (1 Thessalonians 1:3, Romans 8:28, Jeremiah 29:11).",
  "I can do all things through Christ who strengthens me. (Philippians 4:13)",
  "Be still and know that I am God. (Psalm 46:10)",
  "Trust in the Lord with all your heart. (Proverbs 3:5)",
  "The Lord is my light and my salvation; whom shall I fear? (Psalm 27:1)",
  "For I know the plans I have for you, says the Lord. (Jeremiah 29:11)",
  "Come to me, all you who are weary, and I will give you rest. (Matthew 11:28)",
  "Love one another as I have loved you. (John 15:12)",
  "Do not be anxious about anything, but in every situation, present your requests to God. (Philippians 4:6)",
  "The Lord bless you and keep you. (Numbers 6:24)",
  "With God all things are possible. (Matthew 19:26)",
];

const GOALS = [
  "Through Christ I'll become wealthy and provide an extraordinary life for my family.",
  "I will build my business today as an act of stewardship, knowing God is my ultimate provider (Deuteronomy 8:18).",
  "I will work with excellence today because my business is the vehicle God has given me to bless my family and the world.",
  "I will remember today that every client, every deal, and every dollar is a gift of grace through Christ.",
  "I will be the husband and father first, and the businessman second, in every decision I make today.",
  "I will provide my wife and children with a life of abundance, security, and beauty as a reflection of the Father's generosity.",
  "I will build wealth not to be served, but to serve — my family, my Church, and my community.",
  "I will tithe faithfully and fund Catholic causes and missions as a first act, not an afterthought.",
  "I will give generously to those in need today, knowing I cannot out-give God (Luke 6:38).",
  "I will work toward owning a home worthy of the family God has entrusted to me.",
  "I will build real estate and lasting assets so that my children's children inherit a foundation of security.",
  "I will take my family to extraordinary places and create memories that make them feel deeply loved and cared for.",
  "I will start and sustain charities that feed the hungry, shelter the homeless, and restore dignity to the forgotten.",
  "I will fund youth sports teams and give children in my community the opportunities I want for my own kids.",
  "I will be known in my Church community as someone who shows up and gives generously without recognition.",
  "I will be known in my neighbourhood as someone whose success lifts others, not just himself.",
  "I will never forget where I came from or who brought me to where I am going (Deuteronomy 8:18).",
  "I will let success make me more humble, more generous, and more grateful — not harder or prouder.",
  "I will keep my identity rooted in being a child of God, not in my net worth or my achievements.",
  "I will pray before every major business decision, surrendering my plans to God's will (Proverbs 16:3).",
  "I will be the same man in private that I am in public — grounded, faithful, and generous.",
  "I will raise children who understand that wealth is a responsibility and a gift, not a right.",
  "I will never stop building because there are always more people to help, more mouths to feed, more lives to change.",
  "I will hold everything I own with an open hand, knowing it belongs to God and I am only the steward.",
];
